export const Dialogues = {
  Wellcome: "خوش آمدید",
  inputemptyerr: "inputs empty",
  submitbtn: "ورود",
  welcomeToTerme: "به سیستم انتخاب واحد ترمه خوش آمدید",
  emailPlaceholder: "پست الکترونیکی",
  emailFormatError: "مشکلی در فرمت پست الکترونیکی وجود دارد",
  signup: "ثبت نام",
  passwordplc: "گذرواژه",
  passwordConfirmPlaceholder: "تکرار گذرواژه",
  haveproblemerr: "have a problem",
  loginokerr: "all right, you logged in now!",
  exitedSuccessfully: "با موفقیت خارج شدید",
  loginfielderr: "login failed. please check inputs.",
  fullnamePlaceholder: "نام و نام خانوادگی",
  passwordPlaceholder: "گذرواژه",
  majorPlaceholder: " رشته تحصیلی",
  semesterPlaceholder: "ترم تحصیلی",
  studentNumberPlaceholder: "شماره دانشجویی",
  editSubmit: "ویرایش اطلاعات",
  registerSubmit2: "تکمیل عضویت",
  cantBeEmpty: "نمی تواند خالی باشد",
  yourInfoIsSubmitted: "مشخصات جدید شما در سیستم به ثبت رسید.",
  till: "تا",
  updatedYourInfoSuccessfully: " مشخصات شما به روز شد",
  saturday: "شنبه",
  do: "کنید",
  sunday: "یکشنبه",
  monday: "دوشنبه",
  tuesday: "سه شنبه",
  wednesday: "چهارشنبه",
  thursday: "پنج شنبه",
  friday: "جمعه",
  or: "یا",
  courseSearcher: "جستجوگر درس",
  toSystem: "به سیستم",
  typeTheCourseName: " نام درس را تایپ کنید",
  enter: "ورود",
  wrongEmailFormat: "فرمت پست الکترونیکی وارد شده نادرست است",
  emailCantBeEmpty: "پست الکترونیکی نمی تواند خالی باشد",
  userWithThisEmailAlreadyExists: "کاربر با این ایمیل موجود است",
  general: "عمومی",
  shouldBeMoreThanFourCharacters: " اشتباه است.بیشتر از 4 کاراکتر وارد کنید",
  wrongMajor: "رشته وارد شده صحیح نمیباشد",
  unitSelectorSystem: "سیستم شبیه ساز انتخاب واحد",
  kharazmiUniversity: "دانشگاه خوارزمی",
  courses: "دروس",
  serverError: "خطا در سرور ! لطفا بعدا اقدام کنید",
  userWithThisUsernameAlreadyExists: "حساب کاربری با این نام کاربری موجود است",
  chart: "چارت",
  isWrong: "اشتباه است",
  forKharazmiStudents: "    برای دانشجویان : دانشگاه خوارزمی",
  course: "درس",
  teacher: "استاد",
  error: "خطا",
  time: "زمان",
  userAlreadyExists: "کاربر دیگری با این نام وجود دارد",
  loading: "در حال بارگذاری",
  searchOrChoose: "جستجو کنید یا انتخاب کنید",
  specialized: "تخصصی",
  wrongUsernameOrPassword: "نام کاربری یا رمز عبور شما اشتباه است",
  more: "بیشتر",
  homePage: "صفحه اصلی",
  editInfo: " ویرایش اطلاعات",
  notFoundPage: "متاسفانه صفحه مورد نظر وجود نداری",
  exit: "خروج",
  takeTheCourse: "   اخذ کلاس",
  hasConflictWith: "  تداخل زمانی با درس",
  errorHappenedWhileDeleting: "مشکلی در حذف پیش آمد",
  somethingWentWrong: "مشکلی پیش آمد",
  wasDeletedSuccessfully: "با موفقیت حذف شد",
  wasAddedSuccessfully: "با موفقیت افزوده شد",
  cantTakeThisCourse: "امکان اخذ این درس وجود ندارد",
  termeUnitSelectorSystem: "سیستم انتخاب واحد ترمه",
};

export const weekDays = {
  1: "شنبه",
  2: "یک شنبه",
  3: "دو شنبه",
  4: "سه شنبه",
  5: "چهار شنبه",
  6: "پنج شنبه",
};

export const dayTimes = {
  1: "8 تا 10",
  2: "10 تا 12",
  3: "13 تا 15",
  4: "15 تا 17",
};
